#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

OAS_CHANGES=$(git diff --cached --name-only --diff-filter=ACM api/ | wc -l)
if [ $OAS_CHANGES -gt 0 ]
then
    echo "Changes detected in api/, regenerating api/generated/openapi.json"
    yarn oas:lint:redocly
    yarn oas:lint:spectral
    yarn oas:bundle
    git add api/generated/openapi.json
    yarn oas:render
    git add api/generated/openapi.html
    yarn oas:codegen:types
    git add internal/api/types.go
    yarn oas:codegen:server
    git add internal/api/server.go
    echo "OAS Contract Successfully regenerated at api/generated/openapi.json and api/api.gen.go"
else
    echo "No changes detected in api/"
fi
