apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kadok.fullname" . }}
  annotations:
    {{- include "kadok.annotations" . | nindent 4 }}
  labels:
    {{- include "kadok.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kadok.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "kadok.annotations" . | nindent 8 }}
      labels:
        {{- include "kadok.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token-kadok
                  key: token
          volumeMounts:
            {{- if .Values.kadok.properties }}
            - name: config-properties
              mountPath: go/app/configs/properties.yaml
              subPath: properties.yaml
              readOnly: true
            {{- end }}
            {{- if .Values.kadok.roles }}
            - name: config-roles
              mountPath: go/app/configs/roles.yaml
              subPath: roles.yaml
              readOnly: true
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.kadok.properties }}
        - name: config-properties
          configMap:
            name: {{ include "kadok.fullname" . }}-properties
        {{- end }}
        {{- if .Values.kadok.roles }}
        - name: config-roles
          configMap:
            name: {{ include "kadok.fullname" . }}-roles
        {{- end }}
