{{- if .Values.registrySecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrySecret.name }}
  labels:
    {{- include "kadok.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end}}
