{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kadok.serviceAccountName" . }}
  labels:
    {{- include "kadok.labels" . | nindent 4 }}
  {{- with .Values.kadok.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
