title: Kadok
remote_theme: just-the-docs/just-the-docs
description: "Where's Kadoc? Is he well hidden?"
footer_content: "Kadok is maintained by the team of \"Les Petits Pédestres\" under the <a href=\"https://github.com/terag/kadok/blob/master/LICENSE\">GNU GENERAL PUBLIC LICENSE Version 3.</a>"
color_scheme: nil
search_enabled: false
heading_anchors: true
baseurl: ""
url: "https://kadok.pedestres.fr"
aux_links:
  "Kadok on GitHub":
    - "//github.com/terag/kadok"
