#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

OAS_CHANGES=$(git diff --cached --name-only --diff-filter=ACM oas/ | wc -l)
if [ $OAS_CHANGES -gt 0 ]
then
    echo "Changes detected in oas/, regenerating oas/generated/openapi.json"
    yarn oas:lint:redocly
    yarn oas:lint:spectral
    yarn oas:bundle
    git add oas/generated/openapi.json
    yarn oas:render
    git add oas/generated/openapi.html
    yarn oas:codegen:types
    git add api/types.go
    yarn oas:codegen:server
    git add api/server.go
    echo "OAS Contract Successfully regenerated at oas/generated/openapi.json and api/api.gen.go"
else
    echo "No changes detected in oas/"
fi
