# Default values for kadok.

# For retrieving kadok image
image:
  repository: gitlab.beyond-undefined.fr:5050/bots/kadok
  pullPolicy: Always
  tag: latest

# The pullSecrets to use for retrieving Kadok's image
imagePullSecrets:
  - name: ""

# If the registry secret does not yet exist in the cluster, create one
registrySecret:
  create: false
  name: regcred-kadok
  registry: ""
  username: kubernetes
  password: ""

# Kadok specific variables
kadok:
  # The discord token created from https://discord.com/developers/applications.
  # The bot needs it in order to connect to discord APIs and interact with guild members.
  token: ""
  configs: "config-staging"

resources:
  limits:
    cpu: 200m
    memory: 246Mi
  requests:
    cpu: 100m
    memory: 128Mi

strategyType: RollingUpdate

# Gitlab environment variables if you run kadok in a cluster managed with gitlab
# gitlab:
#  env: ""
#  app: ""
